---
name: PlayScript
version: 1.2.0
main: LadinoXx\PlayScript\Main
description: "run real-time php files on your server!"
api: 4.0.0
src-namespace-prefix: LadinoXx\PlayScript
permissions:
 playscript.command:
  description: "run codes"
  default: OP
...
